steps:
  - label: Lint and check formatting
    command: |
      nix-build -A lint -o lint.sh
      ./lint.sh
    timeout: 100
  - label: Build and test on GHC 8.4
    command: |
      nix-build -A monad-bayes-ghc84 --no-out-link
    timeout: 100
  - label: Build and test on GHC 8.6
    command: |
      nix-build -A monad-bayes-ghc86 --no-out-link
    timeout: 100
  - label: Build and test on GHC 8.8
    command: |
      nix-build -A monad-bayes-ghc88 --no-out-link
    timeout: 100
  - label: Build and test on GHC 8.10
    command: |
      nix-build -A monad-bayes-ghc810 --no-out-link
    timeout: 100
